name: ci

on:
  push:
    branches: [ main ]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build kafka-eagle
        uses: docker/build-push-action@v2
        with:
          context: kafka-eagle
          file: ./kafka-eagle/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kafka-eagle:latest
